class: src.ml.classifier.llm.util.rest.StructuredRequestLLM
params:
  name: nebius-llama-70b
  rest_api_model_name: llama-3.3-70b
  url: "https://api.studio.nebius.com/v1/chat/completions"
  payload:
    model: meta-llama/Llama-3.3-70B-Instruct
    temperature: 0.01
    top_p: 0.99
  request_input_classmethod: "create_nebius_request_input"
  request_output_classmethod: "from_nebius_request"
  request_input_data_extraction: "get_prompt_from_openai_data"
  rate_limit_manager: nebius-llama-70b.yaml