class: src.ml.classifier.llm.util.rest.StructuredRequestLLM
params:
  name: openrouter-llama-8b
  rest_api_model_name: llama-8b
  url: "https://openrouter.ai/api/v1/chat/completions"
  payload:
    model: "meta-llama/llama-3.1-8b-instruct"
    temperature: 0.0
  request_input_classmethod: "create_openrouter_request_input"
  request_output_classmethod: "from_openrouter_request"
  request_input_data_extraction: "get_prompt_from_openai_data"
  rate_limit_manager: "openrouter-llama-8b.yaml"