class: "src.ml.classifier.llm.util.rate_limit.RateLimitManager"
params:
  name: groq-llama-9b
  rate_limits:
    num_req_minute:
      limit: 200
      increment_level: "frequency"
      agg_level: "%Y-%m-%d %H:%M"
      action: "raise"
      waiting_time: 60
    num_token_minute:
      limit: 30000
      increment_level: "token"
      agg_level: "%Y-%m-%d %H:%M"
      action: "wait"
      waiting_time: 30
    num_req_day:
      limit: 300000
      increment_level: "frequency"
      agg_level: "%Y-%m-%d"
      action: "raise"