class: src.OneStageLLM
params:
  use_cache: true
  shuffle_free_llms: false
  unknown_detection_scenario: 'implicit_zeroshot'
  unknown_detection_model_name: llama-3.3-70b
  selector:
    class: src.ml.classifier.llm.util.cosine_selector.CosineSelector
    params:
      mode: "knn"
      n_classes: 3
      n_datapoints: 5
  osr_model:
    paid_llms:
      - groq-llama-70b.yaml
      - nebius-llama-70b.yaml
    