class: src.RandomLLM
params:
  name: "Random"
  unknown_detection_scenario: "explicit_fewshot"
  unknown_detection_model_name: random
  selector:
    class: src.ml.classifier.llm.util.cosine_selector.CosineSelector
    params:
      mode: "random_class"
      n_classes: 3
      n_datapoints: 5 