class: src.TwoStageLLM
params:
  skip_unknown_detection: false
  selector:
    class: src.ml.classifier.llm.util.cosine_selector.CosineSelector
    params:
  unknown_detection_model:
    name: llama-70b
    request_output_formatter: 
      function: src.ml.classifier.llm.util.request.RequestOutput.from_llama_hf_request
      params:
    request_input:
      function: src.ml.classifier.llm.util.request.RequestInputData.create_hf_llama_request_input
      params:
        url: https://api-inference.huggingface.co/models/meta-llama/Meta-Llama-3-70b-Instruct
        payload:
          temperature: 1.0
          top_k: 50
          top_p: 0.9 # "nucleus sampling"
  classifier_model:
    name: llama-70b
    request_output_formatter: 
      function: src.ml.classifier.llm.util.request.RequestOutput.from_llama_hf_request
      params:
    request_input:
      function: src.ml.classifier.llm.util.request.RequestInputData.create_hf_llama_request_input
      params:
        url: https://api-inference.huggingface.co/models/meta-llama/Meta-Llama-3-70b-Instruct
        payload:
          temperature: 1.0
          top_k: 50
          top_p: 0.9 # "nucleus sampling"
